// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: messages.proto

#include "messages.pb.h"
#include "messages.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace sse {

static const char* sgx_sse_method_names[] = {
  "/sse.sgx_sse/init_enclave",
  "/sse.sgx_sse/destroy_enclave",
  "/sse.sgx_sse/init_sse",
  "/sse.sgx_sse/generate_session_key",
  "/sse.sgx_sse/remote_attestation_begin",
  "/sse.sgx_sse/remote_attestation_msg0",
  "/sse.sgx_sse/remote_attestation_msg2",
  "/sse.sgx_sse/remote_attestation_final",
  "/sse.sgx_sse/seal_and_save_data",
  "/sse.sgx_sse/read_and_unseal_data",
  "/sse.sgx_sse/close_connection",
  "/sse.sgx_sse/add_record",
  "/sse.sgx_sse/delete_record",
  "/sse.sgx_sse/search_w",
};

std::unique_ptr< sgx_sse::Stub> sgx_sse::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< sgx_sse::Stub> stub(new sgx_sse::Stub(channel, options));
  return stub;
}

sgx_sse::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_init_enclave_(sgx_sse_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_destroy_enclave_(sgx_sse_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_init_sse_(sgx_sse_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_generate_session_key_(sgx_sse_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_remote_attestation_begin_(sgx_sse_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_remote_attestation_msg0_(sgx_sse_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_remote_attestation_msg2_(sgx_sse_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_remote_attestation_final_(sgx_sse_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_seal_and_save_data_(sgx_sse_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_read_and_unseal_data_(sgx_sse_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_close_connection_(sgx_sse_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_add_record_(sgx_sse_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_delete_record_(sgx_sse_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_search_w_(sgx_sse_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status sgx_sse::Stub::init_enclave(::grpc::ClientContext* context, const ::sse::InitRequest& request, ::sse::InitReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sse::InitRequest, ::sse::InitReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_init_enclave_, context, request, response);
}

void sgx_sse::Stub::async::init_enclave(::grpc::ClientContext* context, const ::sse::InitRequest* request, ::sse::InitReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sse::InitRequest, ::sse::InitReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_init_enclave_, context, request, response, std::move(f));
}

void sgx_sse::Stub::async::init_enclave(::grpc::ClientContext* context, const ::sse::InitRequest* request, ::sse::InitReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_init_enclave_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sse::InitReply>* sgx_sse::Stub::PrepareAsyncinit_enclaveRaw(::grpc::ClientContext* context, const ::sse::InitRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::sse::InitReply, ::sse::InitRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_init_enclave_, context, request);
}

::grpc::ClientAsyncResponseReader< ::sse::InitReply>* sgx_sse::Stub::Asyncinit_enclaveRaw(::grpc::ClientContext* context, const ::sse::InitRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncinit_enclaveRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status sgx_sse::Stub::destroy_enclave(::grpc::ClientContext* context, const ::sse::DestroyRequest& request, ::sse::DestroyReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sse::DestroyRequest, ::sse::DestroyReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_destroy_enclave_, context, request, response);
}

void sgx_sse::Stub::async::destroy_enclave(::grpc::ClientContext* context, const ::sse::DestroyRequest* request, ::sse::DestroyReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sse::DestroyRequest, ::sse::DestroyReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_destroy_enclave_, context, request, response, std::move(f));
}

void sgx_sse::Stub::async::destroy_enclave(::grpc::ClientContext* context, const ::sse::DestroyRequest* request, ::sse::DestroyReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_destroy_enclave_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sse::DestroyReply>* sgx_sse::Stub::PrepareAsyncdestroy_enclaveRaw(::grpc::ClientContext* context, const ::sse::DestroyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::sse::DestroyReply, ::sse::DestroyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_destroy_enclave_, context, request);
}

::grpc::ClientAsyncResponseReader< ::sse::DestroyReply>* sgx_sse::Stub::Asyncdestroy_enclaveRaw(::grpc::ClientContext* context, const ::sse::DestroyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdestroy_enclaveRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status sgx_sse::Stub::init_sse(::grpc::ClientContext* context, const ::sse::SSEInitRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sse::SSEInitRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_init_sse_, context, request, response);
}

void sgx_sse::Stub::async::init_sse(::grpc::ClientContext* context, const ::sse::SSEInitRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sse::SSEInitRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_init_sse_, context, request, response, std::move(f));
}

void sgx_sse::Stub::async::init_sse(::grpc::ClientContext* context, const ::sse::SSEInitRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_init_sse_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* sgx_sse::Stub::PrepareAsyncinit_sseRaw(::grpc::ClientContext* context, const ::sse::SSEInitRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::sse::SSEInitRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_init_sse_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* sgx_sse::Stub::Asyncinit_sseRaw(::grpc::ClientContext* context, const ::sse::SSEInitRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncinit_sseRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status sgx_sse::Stub::generate_session_key(::grpc::ClientContext* context, const ::sse::InitRequest& request, ::sse::InitReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sse::InitRequest, ::sse::InitReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_generate_session_key_, context, request, response);
}

void sgx_sse::Stub::async::generate_session_key(::grpc::ClientContext* context, const ::sse::InitRequest* request, ::sse::InitReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sse::InitRequest, ::sse::InitReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_generate_session_key_, context, request, response, std::move(f));
}

void sgx_sse::Stub::async::generate_session_key(::grpc::ClientContext* context, const ::sse::InitRequest* request, ::sse::InitReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_generate_session_key_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sse::InitReply>* sgx_sse::Stub::PrepareAsyncgenerate_session_keyRaw(::grpc::ClientContext* context, const ::sse::InitRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::sse::InitReply, ::sse::InitRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_generate_session_key_, context, request);
}

::grpc::ClientAsyncResponseReader< ::sse::InitReply>* sgx_sse::Stub::Asyncgenerate_session_keyRaw(::grpc::ClientContext* context, const ::sse::InitRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgenerate_session_keyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status sgx_sse::Stub::remote_attestation_begin(::grpc::ClientContext* context, const ::sse::InitialMessage& request, ::sse::Message0* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sse::InitialMessage, ::sse::Message0, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_remote_attestation_begin_, context, request, response);
}

void sgx_sse::Stub::async::remote_attestation_begin(::grpc::ClientContext* context, const ::sse::InitialMessage* request, ::sse::Message0* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sse::InitialMessage, ::sse::Message0, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_remote_attestation_begin_, context, request, response, std::move(f));
}

void sgx_sse::Stub::async::remote_attestation_begin(::grpc::ClientContext* context, const ::sse::InitialMessage* request, ::sse::Message0* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_remote_attestation_begin_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sse::Message0>* sgx_sse::Stub::PrepareAsyncremote_attestation_beginRaw(::grpc::ClientContext* context, const ::sse::InitialMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::sse::Message0, ::sse::InitialMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_remote_attestation_begin_, context, request);
}

::grpc::ClientAsyncResponseReader< ::sse::Message0>* sgx_sse::Stub::Asyncremote_attestation_beginRaw(::grpc::ClientContext* context, const ::sse::InitialMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncremote_attestation_beginRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status sgx_sse::Stub::remote_attestation_msg0(::grpc::ClientContext* context, const ::sse::Message0& request, ::sse::Message1* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sse::Message0, ::sse::Message1, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_remote_attestation_msg0_, context, request, response);
}

void sgx_sse::Stub::async::remote_attestation_msg0(::grpc::ClientContext* context, const ::sse::Message0* request, ::sse::Message1* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sse::Message0, ::sse::Message1, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_remote_attestation_msg0_, context, request, response, std::move(f));
}

void sgx_sse::Stub::async::remote_attestation_msg0(::grpc::ClientContext* context, const ::sse::Message0* request, ::sse::Message1* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_remote_attestation_msg0_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sse::Message1>* sgx_sse::Stub::PrepareAsyncremote_attestation_msg0Raw(::grpc::ClientContext* context, const ::sse::Message0& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::sse::Message1, ::sse::Message0, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_remote_attestation_msg0_, context, request);
}

::grpc::ClientAsyncResponseReader< ::sse::Message1>* sgx_sse::Stub::Asyncremote_attestation_msg0Raw(::grpc::ClientContext* context, const ::sse::Message0& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncremote_attestation_msg0Raw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status sgx_sse::Stub::remote_attestation_msg2(::grpc::ClientContext* context, const ::sse::Message2& request, ::sse::Message3* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sse::Message2, ::sse::Message3, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_remote_attestation_msg2_, context, request, response);
}

void sgx_sse::Stub::async::remote_attestation_msg2(::grpc::ClientContext* context, const ::sse::Message2* request, ::sse::Message3* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sse::Message2, ::sse::Message3, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_remote_attestation_msg2_, context, request, response, std::move(f));
}

void sgx_sse::Stub::async::remote_attestation_msg2(::grpc::ClientContext* context, const ::sse::Message2* request, ::sse::Message3* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_remote_attestation_msg2_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sse::Message3>* sgx_sse::Stub::PrepareAsyncremote_attestation_msg2Raw(::grpc::ClientContext* context, const ::sse::Message2& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::sse::Message3, ::sse::Message2, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_remote_attestation_msg2_, context, request);
}

::grpc::ClientAsyncResponseReader< ::sse::Message3>* sgx_sse::Stub::Asyncremote_attestation_msg2Raw(::grpc::ClientContext* context, const ::sse::Message2& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncremote_attestation_msg2Raw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status sgx_sse::Stub::remote_attestation_final(::grpc::ClientContext* context, const ::sse::AttestationMessage& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sse::AttestationMessage, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_remote_attestation_final_, context, request, response);
}

void sgx_sse::Stub::async::remote_attestation_final(::grpc::ClientContext* context, const ::sse::AttestationMessage* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sse::AttestationMessage, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_remote_attestation_final_, context, request, response, std::move(f));
}

void sgx_sse::Stub::async::remote_attestation_final(::grpc::ClientContext* context, const ::sse::AttestationMessage* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_remote_attestation_final_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* sgx_sse::Stub::PrepareAsyncremote_attestation_finalRaw(::grpc::ClientContext* context, const ::sse::AttestationMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::sse::AttestationMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_remote_attestation_final_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* sgx_sse::Stub::Asyncremote_attestation_finalRaw(::grpc::ClientContext* context, const ::sse::AttestationMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncremote_attestation_finalRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status sgx_sse::Stub::seal_and_save_data(::grpc::ClientContext* context, const ::sse::SealRequest& request, ::sse::SealReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sse::SealRequest, ::sse::SealReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_seal_and_save_data_, context, request, response);
}

void sgx_sse::Stub::async::seal_and_save_data(::grpc::ClientContext* context, const ::sse::SealRequest* request, ::sse::SealReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sse::SealRequest, ::sse::SealReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_seal_and_save_data_, context, request, response, std::move(f));
}

void sgx_sse::Stub::async::seal_and_save_data(::grpc::ClientContext* context, const ::sse::SealRequest* request, ::sse::SealReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_seal_and_save_data_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sse::SealReply>* sgx_sse::Stub::PrepareAsyncseal_and_save_dataRaw(::grpc::ClientContext* context, const ::sse::SealRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::sse::SealReply, ::sse::SealRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_seal_and_save_data_, context, request);
}

::grpc::ClientAsyncResponseReader< ::sse::SealReply>* sgx_sse::Stub::Asyncseal_and_save_dataRaw(::grpc::ClientContext* context, const ::sse::SealRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncseal_and_save_dataRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status sgx_sse::Stub::read_and_unseal_data(::grpc::ClientContext* context, const ::sse::UnsealRequest& request, ::sse::UnsealReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sse::UnsealRequest, ::sse::UnsealReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_read_and_unseal_data_, context, request, response);
}

void sgx_sse::Stub::async::read_and_unseal_data(::grpc::ClientContext* context, const ::sse::UnsealRequest* request, ::sse::UnsealReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sse::UnsealRequest, ::sse::UnsealReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_read_and_unseal_data_, context, request, response, std::move(f));
}

void sgx_sse::Stub::async::read_and_unseal_data(::grpc::ClientContext* context, const ::sse::UnsealRequest* request, ::sse::UnsealReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_read_and_unseal_data_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sse::UnsealReply>* sgx_sse::Stub::PrepareAsyncread_and_unseal_dataRaw(::grpc::ClientContext* context, const ::sse::UnsealRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::sse::UnsealReply, ::sse::UnsealRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_read_and_unseal_data_, context, request);
}

::grpc::ClientAsyncResponseReader< ::sse::UnsealReply>* sgx_sse::Stub::Asyncread_and_unseal_dataRaw(::grpc::ClientContext* context, const ::sse::UnsealRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncread_and_unseal_dataRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status sgx_sse::Stub::close_connection(::grpc::ClientContext* context, const ::sse::CloseRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sse::CloseRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_close_connection_, context, request, response);
}

void sgx_sse::Stub::async::close_connection(::grpc::ClientContext* context, const ::sse::CloseRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sse::CloseRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_close_connection_, context, request, response, std::move(f));
}

void sgx_sse::Stub::async::close_connection(::grpc::ClientContext* context, const ::sse::CloseRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_close_connection_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* sgx_sse::Stub::PrepareAsyncclose_connectionRaw(::grpc::ClientContext* context, const ::sse::CloseRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::sse::CloseRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_close_connection_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* sgx_sse::Stub::Asyncclose_connectionRaw(::grpc::ClientContext* context, const ::sse::CloseRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncclose_connectionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status sgx_sse::Stub::add_record(::grpc::ClientContext* context, const ::sse::AddRecordRequest& request, ::sse::AddRecordReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sse::AddRecordRequest, ::sse::AddRecordReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_add_record_, context, request, response);
}

void sgx_sse::Stub::async::add_record(::grpc::ClientContext* context, const ::sse::AddRecordRequest* request, ::sse::AddRecordReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sse::AddRecordRequest, ::sse::AddRecordReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_add_record_, context, request, response, std::move(f));
}

void sgx_sse::Stub::async::add_record(::grpc::ClientContext* context, const ::sse::AddRecordRequest* request, ::sse::AddRecordReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_add_record_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sse::AddRecordReply>* sgx_sse::Stub::PrepareAsyncadd_recordRaw(::grpc::ClientContext* context, const ::sse::AddRecordRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::sse::AddRecordReply, ::sse::AddRecordRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_add_record_, context, request);
}

::grpc::ClientAsyncResponseReader< ::sse::AddRecordReply>* sgx_sse::Stub::Asyncadd_recordRaw(::grpc::ClientContext* context, const ::sse::AddRecordRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncadd_recordRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status sgx_sse::Stub::delete_record(::grpc::ClientContext* context, const ::sse::DeleteRecordRequest& request, ::sse::DeleteRecordReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sse::DeleteRecordRequest, ::sse::DeleteRecordReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_delete_record_, context, request, response);
}

void sgx_sse::Stub::async::delete_record(::grpc::ClientContext* context, const ::sse::DeleteRecordRequest* request, ::sse::DeleteRecordReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sse::DeleteRecordRequest, ::sse::DeleteRecordReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_delete_record_, context, request, response, std::move(f));
}

void sgx_sse::Stub::async::delete_record(::grpc::ClientContext* context, const ::sse::DeleteRecordRequest* request, ::sse::DeleteRecordReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_delete_record_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sse::DeleteRecordReply>* sgx_sse::Stub::PrepareAsyncdelete_recordRaw(::grpc::ClientContext* context, const ::sse::DeleteRecordRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::sse::DeleteRecordReply, ::sse::DeleteRecordRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_delete_record_, context, request);
}

::grpc::ClientAsyncResponseReader< ::sse::DeleteRecordReply>* sgx_sse::Stub::Asyncdelete_recordRaw(::grpc::ClientContext* context, const ::sse::DeleteRecordRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdelete_recordRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status sgx_sse::Stub::search_w(::grpc::ClientContext* context, const ::sse::SearchwRequest& request, ::sse::SearchwReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sse::SearchwRequest, ::sse::SearchwReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_search_w_, context, request, response);
}

void sgx_sse::Stub::async::search_w(::grpc::ClientContext* context, const ::sse::SearchwRequest* request, ::sse::SearchwReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sse::SearchwRequest, ::sse::SearchwReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_search_w_, context, request, response, std::move(f));
}

void sgx_sse::Stub::async::search_w(::grpc::ClientContext* context, const ::sse::SearchwRequest* request, ::sse::SearchwReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_search_w_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sse::SearchwReply>* sgx_sse::Stub::PrepareAsyncsearch_wRaw(::grpc::ClientContext* context, const ::sse::SearchwRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::sse::SearchwReply, ::sse::SearchwRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_search_w_, context, request);
}

::grpc::ClientAsyncResponseReader< ::sse::SearchwReply>* sgx_sse::Stub::Asyncsearch_wRaw(::grpc::ClientContext* context, const ::sse::SearchwRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncsearch_wRaw(context, request, cq);
  result->StartCall();
  return result;
}

sgx_sse::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      sgx_sse_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< sgx_sse::Service, ::sse::InitRequest, ::sse::InitReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](sgx_sse::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sse::InitRequest* req,
             ::sse::InitReply* resp) {
               return service->init_enclave(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      sgx_sse_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< sgx_sse::Service, ::sse::DestroyRequest, ::sse::DestroyReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](sgx_sse::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sse::DestroyRequest* req,
             ::sse::DestroyReply* resp) {
               return service->destroy_enclave(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      sgx_sse_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< sgx_sse::Service, ::sse::SSEInitRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](sgx_sse::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sse::SSEInitRequest* req,
             ::google::protobuf::Empty* resp) {
               return service->init_sse(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      sgx_sse_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< sgx_sse::Service, ::sse::InitRequest, ::sse::InitReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](sgx_sse::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sse::InitRequest* req,
             ::sse::InitReply* resp) {
               return service->generate_session_key(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      sgx_sse_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< sgx_sse::Service, ::sse::InitialMessage, ::sse::Message0, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](sgx_sse::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sse::InitialMessage* req,
             ::sse::Message0* resp) {
               return service->remote_attestation_begin(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      sgx_sse_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< sgx_sse::Service, ::sse::Message0, ::sse::Message1, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](sgx_sse::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sse::Message0* req,
             ::sse::Message1* resp) {
               return service->remote_attestation_msg0(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      sgx_sse_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< sgx_sse::Service, ::sse::Message2, ::sse::Message3, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](sgx_sse::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sse::Message2* req,
             ::sse::Message3* resp) {
               return service->remote_attestation_msg2(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      sgx_sse_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< sgx_sse::Service, ::sse::AttestationMessage, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](sgx_sse::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sse::AttestationMessage* req,
             ::google::protobuf::Empty* resp) {
               return service->remote_attestation_final(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      sgx_sse_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< sgx_sse::Service, ::sse::SealRequest, ::sse::SealReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](sgx_sse::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sse::SealRequest* req,
             ::sse::SealReply* resp) {
               return service->seal_and_save_data(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      sgx_sse_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< sgx_sse::Service, ::sse::UnsealRequest, ::sse::UnsealReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](sgx_sse::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sse::UnsealRequest* req,
             ::sse::UnsealReply* resp) {
               return service->read_and_unseal_data(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      sgx_sse_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< sgx_sse::Service, ::sse::CloseRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](sgx_sse::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sse::CloseRequest* req,
             ::google::protobuf::Empty* resp) {
               return service->close_connection(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      sgx_sse_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< sgx_sse::Service, ::sse::AddRecordRequest, ::sse::AddRecordReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](sgx_sse::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sse::AddRecordRequest* req,
             ::sse::AddRecordReply* resp) {
               return service->add_record(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      sgx_sse_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< sgx_sse::Service, ::sse::DeleteRecordRequest, ::sse::DeleteRecordReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](sgx_sse::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sse::DeleteRecordRequest* req,
             ::sse::DeleteRecordReply* resp) {
               return service->delete_record(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      sgx_sse_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< sgx_sse::Service, ::sse::SearchwRequest, ::sse::SearchwReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](sgx_sse::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sse::SearchwRequest* req,
             ::sse::SearchwReply* resp) {
               return service->search_w(ctx, req, resp);
             }, this)));
}

sgx_sse::Service::~Service() {
}

::grpc::Status sgx_sse::Service::init_enclave(::grpc::ServerContext* context, const ::sse::InitRequest* request, ::sse::InitReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status sgx_sse::Service::destroy_enclave(::grpc::ServerContext* context, const ::sse::DestroyRequest* request, ::sse::DestroyReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status sgx_sse::Service::init_sse(::grpc::ServerContext* context, const ::sse::SSEInitRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status sgx_sse::Service::generate_session_key(::grpc::ServerContext* context, const ::sse::InitRequest* request, ::sse::InitReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status sgx_sse::Service::remote_attestation_begin(::grpc::ServerContext* context, const ::sse::InitialMessage* request, ::sse::Message0* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status sgx_sse::Service::remote_attestation_msg0(::grpc::ServerContext* context, const ::sse::Message0* request, ::sse::Message1* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status sgx_sse::Service::remote_attestation_msg2(::grpc::ServerContext* context, const ::sse::Message2* request, ::sse::Message3* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status sgx_sse::Service::remote_attestation_final(::grpc::ServerContext* context, const ::sse::AttestationMessage* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status sgx_sse::Service::seal_and_save_data(::grpc::ServerContext* context, const ::sse::SealRequest* request, ::sse::SealReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status sgx_sse::Service::read_and_unseal_data(::grpc::ServerContext* context, const ::sse::UnsealRequest* request, ::sse::UnsealReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status sgx_sse::Service::close_connection(::grpc::ServerContext* context, const ::sse::CloseRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status sgx_sse::Service::add_record(::grpc::ServerContext* context, const ::sse::AddRecordRequest* request, ::sse::AddRecordReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status sgx_sse::Service::delete_record(::grpc::ServerContext* context, const ::sse::DeleteRecordRequest* request, ::sse::DeleteRecordReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status sgx_sse::Service::search_w(::grpc::ServerContext* context, const ::sse::SearchwRequest* request, ::sse::SearchwReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace sse

